name = "ITensorGPU"
uuid = "d89171c1-af8f-46b3-badf-d2a472317c15"
authors = ["Katharine Hyatt", "Matthew Fishman <mfishman@flatironinstitute.org>"]
version = "0.2.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"

[compat]
Adapt = "3, 4"
CUDA = "4, 5"
ITensors = "0.3, 0.4, 0.5"
julia = "1.6"
